name: Build and Upload
on:
  push:
    branches:
      - main
      - 'release-*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build-publish-docker-helm:
    name: Build & Publish Docker Image & Helm Chart
    runs-on: ubuntu-latest
    env:
      HELM_CHART_PATH: package/helm/clinic-config-indiadistro
    steps:
      - uses: actions/checkout@v2
      - name: Set env.ARTIFACT_VERSION
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker - Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker - Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: package/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: infoiplitin/clinic-config-indiadistro:${{env.ARTIFACT_VERSION}},infoiplitin/clinic-config-indiadistro:latest
      - name: Pull Bahmni Default Config Helm Chart
        run: |
          helm pull default-config --repo https://bahmni.github.io/helm-charts --devel --untar --untardir package/helm
          mv package/helm/default-config/ package/helm/clinic-config-indiadistro/
      - name: Update Chart values
        run: |
          yq --inplace '.image.repository = "infoiplitin"' $HELM_CHART_PATH/values.yaml
          yq --inplace '.image.name = "clinic-config-indiadistro"' $HELM_CHART_PATH/values.yaml
          yq --inplace '.image.tag = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/values.yaml
          yq --inplace '.version = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/Chart.yaml
          yq --inplace '.name = "clinic-config-indiadistro"' $HELM_CHART_PATH/Chart.yaml
          yq --inplace '.description = "Helm chart for clinic-config-indiadistro of IPLit"' $HELM_CHART_PATH/Chart.yaml

      - name: Helm Lint
        run: helm lint $HELM_CHART_PATH

      - name: Helm Package
        run: helm package $HELM_CHART_PATH

      - name: Helm - Checkout Charts Repository
        uses: actions/checkout@v2
        with:
          repository: IPLit/helm-charts
          ref: gh-pages
          path: helm-charts
          persist-credentials: false

      - name: Helm - Copy chart
        run: mkdir -p helm-charts/clinic-config-indiadistro/ && cp clinic-config-indiadistro-${{ env.ARTIFACT_VERSION }}.tgz helm-charts/clinic-config-indiadistro/

      - name: Helm - reIndex
        working-directory: helm-charts/
        run: helm repo index --merge index.yaml --url https://iplit.github.io/helm-charts/  .

      - name: Helm - Publish Chart
        working-directory: helm-charts/
        run: |
          git config user.name ${{ secrets.BAHMNI_USERNAME}}
          git config user.email ${{ secrets.BAHMNI_EMAIL}}
          git add .
          git commit -m "Release of clinic-config-indiadistro-${{ env.ARTIFACT_VERSION }}"
          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/iplit/helm-charts.git' gh-pages
